[book]
title = "be Rustaceans"
description = "如何成为一名合格的 Rustacean ? 肯定有个过程, 这儿记录了私人这个转化过程..."
authors = ["ZoomQuiet"]
language = "zh"
multilingual = false
src = "src"
base_url = "rs.101.so"

# Enables the `mdbook-template` preprocessor
#[preprocessor.template]

[build]
build-dir = "docs"
create-missing = true

[rss4mdbook]
url_base = "https://rs.101.so"
rss_title = "be Rustaceans ~ 成锈纪"
rss_desc = "~ 汇集 大妈/Zoom.Quiet 学习/实践/探索/... Rust 世界锈迹, 一起成为 Rustacean 吧..."

#[preprocessor.rss]
#files-glob = "src/*.md"
#url-base = "https://rs.101.so/"

[output.html]
#default-theme = "rust"
#site-url = "/mdBook/"
#mathjax-support = true
git-repository-url = "https://github.com/zhrust/rustacean/tree/main/src"
edit-url-template = "https://github.com/zhrust/rustacean/blob/main/src/{path}"
additional-css = ["theme/style.css"]
additional-js = ["assets/custom.js", "assets/bigPicture.js"]

[output.html.fold]
enable = false
level = 1

[output.html.print]
enable = false

[output.html.playground]
editable = true
line-numbers = true
#copy-js = true
[output.theme-ace]
theme-white = "xcode"
theme-dark = "monokai"

[output.html.search]
limit-results = 13
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2

# book.toml
#   230220 ++ cognitive-engineering-lab/aquascope
#   : Interactive visualizations of Rust at compile-time and run-time https://github.com/cognitive-engineering-lab/aquascope
#[preprocessor.aquascope]

[rust]
edition = "2021"
