[book]
title = "be Rustaceans"
description = "如何成为一名合格的 Rustacean ? 肯定有个过程, 这儿记录了私人这个转化过程..."
authors = ["ZoomQuiet"]
#language = "en"
multilingual = false
src = "src"
base_url = "rs.101.so"

# Enables the `mdbook-template` preprocessor
#[preprocessor.template]

[build]
build-dir = "docs"

[preprocessor.rss]
files-glob = "src/*.md"
url-base = "https://rs.101.so/"

[output.html]
additional-css = ["theme/style.css"]
additional-js = ["assets/custom.js", "assets/bigPicture.js"]
git-repository-url = "https://github.com/zhrust/rustacean/tree/main/src"
edit-url-template = "https://github.com/zhrust/rustacean/edit/master/{path}"
#mathjax-support = true
#site-url = "/mdBook/"

#[output.html.playpen]
#line-numbers = true
#editable = true
#editor = "ace"
[output.html.playground]
editable = true
copy-js = true
# line-numbers = true

[output.html.fold]
enable = true
level = 1

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2

# book.toml
#   230220 ++ cognitive-engineering-lab/aquascope
#   : Interactive visualizations of Rust at compile-time and run-time https://github.com/cognitive-engineering-lab/aquascope
#[preprocessor.aquascope]

[rust]
edition = "2021"
